package com.example.model

import androidx.compose.ui.graphics.Color

enum class ThemePreset(
    val title: String,
    val background: Color,
    val foreground: Color,
    val cursor: Color,
    val selection: Color,
    val promptColor: Color,
    val ansiBlack: Color,
    val ansiRed: Color,
    val ansiGreen: Color,
    val ansiYellow: Color,
    val ansiBlue: Color,
    val ansiMagenta: Color,
    val ansiCyan: Color,
    val ansiWhite: Color,
    val ansiBrightBlack: Color,
    val ansiBrightRed: Color,
    val ansiBrightGreen: Color,
    val ansiBrightYellow: Color,
    val ansiBrightBlue: Color,
    val ansiBrightMagenta: Color,
    val ansiBrightCyan: Color,
    val ansiBrightWhite: Color
) {
    DARK_CLASSIC(
        title = "Classic Dark",
        background = Color(0xFF0F141C),
        foreground = Color(0xFFE6EDF3),
        cursor = Color(0xFF58A6FF),
        selection = Color(0x4058A6FF),
        promptColor = Color(0xFF3FB950),
        ansiBlack = Color(0xFF484F58),
        ansiRed = Color(0xFFFF7B72),
        ansiGreen = Color(0xFF3FB950),
        ansiYellow = Color(0xFFD29922),
        ansiBlue = Color(0xFF58A6FF),
        ansiMagenta = Color(0xFFBC8CFF),
        ansiCyan = Color(0xFF39C5CF),
        ansiWhite = Color(0xFFB1BAC4),
        ansiBrightBlack = Color(0xFF6E7681),
        ansiBrightRed = Color(0xFFFFA198),
        ansiBrightGreen = Color(0xFF56D364),
        ansiBrightYellow = Color(0xFFE3B341),
        ansiBrightBlue = Color(0xFF79C0FF),
        ansiBrightMagenta = Color(0xFFD2A8FF),
        ansiBrightCyan = Color(0xFF56D4DD),
        ansiBrightWhite = Color(0xFFF0F6FC)
    ),

    CYBER_MATRIX(
        title = "Cyber Matrix",
        background = Color(0xFF050B05),
        foreground = Color(0xFF00FF66),
        cursor = Color(0xFF00FF66),
        selection = Color(0x5500FF66),
        promptColor = Color(0xFF00E5FF),
        ansiBlack = Color(0xFF1B381B),
        ansiRed = Color(0xFFFF0055),
        ansiGreen = Color(0xFF00FF66),
        ansiYellow = Color(0xFFFFEE00),
        ansiBlue = Color(0xFF00B0FF),
        ansiMagenta = Color(0xFFFF00CC),
        ansiCyan = Color(0xFF00E5FF),
        ansiWhite = Color(0xFFCCFFDD),
        ansiBrightBlack = Color(0xFF2E632E),
        ansiBrightRed = Color(0xFFFF3377),
        ansiBrightGreen = Color(0xFF33FF88),
        ansiBrightYellow = Color(0xFFFFFF33),
        ansiBrightBlue = Color(0xFF33C2FF),
        ansiBrightMagenta = Color(0xFFFF33D6),
        ansiBrightCyan = Color(0xFF33EBFF),
        ansiBrightWhite = Color(0xFFFFFFFF)
    ),

    MONOKAI_PRO(
        title = "Monokai Pro",
        background = Color(0xFF2D2A2E),
        foreground = Color(0xFFFCFCFA),
        cursor = Color(0xFFFFD866),
        selection = Color(0x40FFD866),
        promptColor = Color(0xFFFF6188),
        ansiBlack = Color(0xFF403E41),
        ansiRed = Color(0xFFFF6188),
        ansiGreen = Color(0xFFA9DC76),
        ansiYellow = Color(0xFFFFD866),
        ansiBlue = Color(0xFFFC9867),
        ansiMagenta = Color(0xFFAB9DF2),
        ansiCyan = Color(0xFF78DCE8),
        ansiWhite = Color(0xFFFCFCFA),
        ansiBrightBlack = Color(0xFF727072),
        ansiBrightRed = Color(0xFFFF6188),
        ansiBrightGreen = Color(0xFFA9DC76),
        ansiBrightYellow = Color(0xFFFFD866),
        ansiBrightBlue = Color(0xFFFC9867),
        ansiBrightMagenta = Color(0xFFAB9DF2),
        ansiBrightCyan = Color(0xFF78DCE8),
        ansiBrightWhite = Color(0xFFFFFFFF)
    ),

    DRACULA(
        title = "Dracula",
        background = Color(0xFF282A36),
        foreground = Color(0xFFF8F8F2),
        cursor = Color(0xFFFF79C6),
        selection = Color(0x40BD93F9),
        promptColor = Color(0xFF50FA7B),
        ansiBlack = Color(0xFF21222C),
        ansiRed = Color(0xFFFF5555),
        ansiGreen = Color(0xFF50FA7B),
        ansiYellow = Color(0xFFF1FA8C),
        ansiBlue = Color(0xFFBD93F9),
        ansiMagenta = Color(0xFFFF79C6),
        ansiCyan = Color(0xFF8BE9FD),
        ansiWhite = Color(0xFFF8F8F2),
        ansiBrightBlack = Color(0xFF6272A4),
        ansiBrightRed = Color(0xFFFF6E6E),
        ansiBrightGreen = Color(0xFF69FF94),
        ansiBrightYellow = Color(0xFFFFFFA5),
        ansiBrightBlue = Color(0xFFD6ACFF),
        ansiBrightMagenta = Color(0xFFFF92DF),
        ansiBrightCyan = Color(0xFFA4FFFF),
        ansiBrightWhite = Color(0xFFFFFFFF)
    ),

    SOLARIZED_DARK(
        title = "Solarized Dark",
        background = Color(0xFF002B36),
        foreground = Color(0xFF839496),
        cursor = Color(0xFF268BD2),
        selection = Color(0x40268BD2),
        promptColor = Color(0xFF859900),
        ansiBlack = Color(0xFF073642),
        ansiRed = Color(0xFFDC322F),
        ansiGreen = Color(0xFF859900),
        ansiYellow = Color(0xFFB58900),
        ansiBlue = Color(0xFF268BD2),
        ansiMagenta = Color(0xFFD33682),
        ansiCyan = Color(0xFF2AA198),
        ansiWhite = Color(0xFFEEE8D5),
        ansiBrightBlack = Color(0xFF586E75),
        ansiBrightRed = Color(0xFFCB4B16),
        ansiBrightGreen = Color(0xFF586E75),
        ansiBrightYellow = Color(0xFF657B83),
        ansiBrightBlue = Color(0xFF839496),
        ansiBrightMagenta = Color(0xFF6C71C4),
        ansiBrightCyan = Color(0xFF93A1A1),
        ansiBrightWhite = Color(0xFFFDF6E3)
    ),

    RETRO_AMBER(
        title = "Retro Amber CRT",
        background = Color(0xFF140D00),
        foreground = Color(0xFFFFB000),
        cursor = Color(0xFFFFC000),
        selection = Color(0x40FFB000),
        promptColor = Color(0xFFFFCC00),
        ansiBlack = Color(0xFF332000),
        ansiRed = Color(0xFFFF6600),
        ansiGreen = Color(0xFFFFB000),
        ansiYellow = Color(0xFFFFD000),
        ansiBlue = Color(0xFFFFAA33),
        ansiMagenta = Color(0xFFFF8800),
        ansiCyan = Color(0xFFFFCC66),
        ansiWhite = Color(0xFFFFE099),
        ansiBrightBlack = Color(0xFF553800),
        ansiBrightRed = Color(0xFFFF7722),
        ansiBrightGreen = Color(0xFFFFC022),
        ansiBrightYellow = Color(0xFFFFE044),
        ansiBrightBlue = Color(0xFFFFBB55),
        ansiBrightMagenta = Color(0xFFFF9922),
        ansiBrightCyan = Color(0xFFFFDD88),
        ansiBrightWhite = Color(0xFFFFF0CC)
    )
}
